# Copy this file as "config.yaml", and fill in the values as appropriate.
# ------------------------------------------------------------------------------

# How often to check for new virtual lives in hours
# 0 means disabled
refreshIntervalHours: 4

# The channel ID where to send a message if new virtual lives are found
# Must be a string
# null to disable
newLivesChannel:

# Text to put in a message notifying of new virtual lives, used in conjunction with newLivesChannel
# null to disable (only embed)
newMessageContent:

sekaiServers:
  English: "https://raw.githubusercontent.com/Sekai-World/sekai-master-db-en-diff/main/virtualLives.json"
  Japanese: "https://raw.githubusercontent.com/Sekai-World/sekai-master-db-diff/main/virtualLives.json"
  # Korean: "https://raw.githubusercontent.com/Sekai-World/sekai-master-db-kr-diff/main/virtualLives.json"
  # Taiwanese: "https://raw.githubusercontent.com/Sekai-World/sekai-master-db-tc-diff/main/virtualLives.json"

#  ***** For the url, put %s where your username and password go! *****
# For example: mongodb+srv://%s:%s@example.com/example?example=example
# agendaCollection is where the jobs are stored.
# virtualLiveCollection_prefix is the prefix for where the virtual live and associated data is stored
#     the suffix is the region defined in sekaiServers
mongoDb:
  url:
  user:
  password:
  agendaCollection: virtualLiveAgendaCollection
  virtualLiveCollection_prefix: virtualLiveDataCollection_
